name: Testing - CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "*"

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: create .npmrc file
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
    - name: Install nestjs cli
      run: npm i -g @nestjs/cli
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Run tests
      run: npm run test:cov
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}